name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    
    - name: Set up Python
      run: uv python install 3.12
    
    - name: Install dependencies
      run: |
        uv sync --extra dev
    
    - name: Run ruff linting
      run: |
        uv run ruff check .
    
    - name: Run mypy type checking
      run: |
        uv run mypy . --ignore-missing-imports
      continue-on-error: true  # Allow mypy to fail while we're improving type coverage
    
    - name: Run tests
      run: |
        # Run tests only if they exist
        if [ -f "test_basic.py" ]; then uv run python test_basic.py; fi
        if [ -f "test_production_dry_run.py" ]; then uv run python test_production_dry_run.py; fi
        if [ -f "email_service.py" ]; then uv run python email_service.py; fi
      continue-on-error: true  # Some tests may require external services
    
    - name: Validate configuration
      run: |
        # Validate config files only if they exist
        if [ -f "sample_config.json" ]; then uv run python -c "import json; json.load(open('sample_config.json'))"; fi
        if [ -f "sample_account_details.json" ]; then uv run python -c "import json; json.load(open('sample_account_details.json'))"; fi
    
    - name: Test justfile commands
      run: |
        # Test justfile only if it exists
        if [ -f "justfile" ]; then
          # Install just
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin
          just install
          # Run validation if command exists
          if just --list | grep -q "validate"; then just validate; fi
        fi